### ISSUE TITLE
Turn Js Sliderbar 

### ISSUE THREAD

**Issue by Lalaland245** [mverleg/svsite#142]
I am creating a Flipbook using HTML CSS and turn.js and I wanted to ask how I can add a simple slider bar. I am relatively new to coding so an existing code that I could use would be great!

Thanks :)

**Comment by mverleg** [comment]
I'm sorry, maybe [this page](https://www.w3schools.com/howto/howto_js_rangeslider.asp) or stackoverflow can help? It's not really related to this project and this has been inactive for years...
